### ISSUE TITLE
Build images for all dependencies before running the workflow

### ISSUE THREAD

**Issue by grighetto** [datastax/adelphi#32]
Up until now, we've been building all the dependencies that have no official Docker images on the fly (Gemini, Spark, cassandra-diff) within the k8s cluster itself at every execution of Adelphi in order to have a consistent and simple experience locally or across cloud envs, but as we add more tools, the startup time adds up.

Instead, we should start by at least providing Dockerfiles such that one could build these images once and reuse them locally with k3d. Later, we could publish these images to a public registry.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/AD-85) by [Unito](https://www.unito.io)
┆Issue Number: AD-85

**Comment by grighetto** [comment]
If we want to guarantee a test run to be reproducible for a long time, we need the tools we use to be available. Things like cassandra-diff and Gemini have no official public images.
We should consider building and publishing them.

**Comment by absurdfarce** [comment]
This seems like another argument for building "fatter" images which already contain the tools.  The image itself functions as a "checkpoint" for the combination of the specific tools in question.

An example: I'm imagining migrating the current "spark-image" template to an image which already has a precise version of Spark + cassandra-diff installed.  This image is itself versioned, which means we can explicitly say that a user running v1.2.3 of the image is using Spark 3.0.1 and cassandra-diff foo [1].  This change alone _greatly_ facilitates reproducibility and general uniformity.  It also makes everything run faster (under the assumption that the increase in download times for a larger image is more than offset by the removal of the need to download, build and install individual binaries as is done in the current workflow).

[1] Since cassandra-diff doesn't have explicit releases, or at least don't yet, this likely equates to a git hash

**Comment by grighetto** [comment]
@absurdfarce Those are all good points, thanks!

I think I'd prefer individual images per tool instead of a fat image with everything for a couple of reasons:
1- some users may choose not to run all the available tools, so they could download just the images they need. That makes for smaller images and faster downloads.
2- provides isolation of dependencies - for example, some tools require newer versions of the JVM to run, so if they live in different images, we don't have to worry about clashes or incompatibilities.
I agree with the specific example of Spark and cassandra-diff though, because they to have to be in the same image (the cassandra-diff jars have to be in the Spark classpath).

What I'm envisioning is that the top-level version would be at the Helm chart level and its YAML files would point to (pin) specific versions of the tools' images.
